apiVersion: v1
kind: Service
metadata:
  name: mlops-flask-api
  labels:
    app: mlops-flask-api
    component: prediction-api
spec:
  type: ClusterIP
  selector:
    app: mlops-flask-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
