from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPORT_DIR = Path("reports/security")
DEPENDENCY_REPORT = REPORT_DIR / "dependency_scan.txt"
SECRET_REPORT = REPORT_DIR / "secret_scan.txt"
DOCKER_REPORT = REPORT_DIR / "docker_security_notes.md"
SBOM_REPORT = REPORT_DIR / "sbom.spdx.json"

IGNORED_DIRS = {
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "venv",
}
IGNORED_FILES = {
    "models/wine_quality_classifier.joblib",
    "scripts/security_scan.py",
    "tests/test_workflows.py",
    "Makefile",
}


def _timestamp() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat()


def _read_requirements(path: Path = Path("requirements.txt")) -> list[tuple[str, str]]:
    packages: list[tuple[str, str]] = []
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if "==" not in line:
            packages.append((line, "unpinned"))
            continue
        name, version = line.split("==", 1)
        packages.append((name.strip(), version.strip()))
    return packages


def _write_dependency_inventory() -> None:
    packages = _read_requirements()
    lines = [
        "Dependency security evidence",
        f"Generated at: {_timestamp()}",
        "Source: requirements.txt",
        "",
        "Pinned dependency inventory:",
    ]
    for name, version in packages:
        lines.append(f"- {name}=={version}")
    lines.extend(
        [
            "",
            "Vulnerability audit command used in GitHub Actions:",
            "python -m pip_audit -r requirements.txt --progress-spinner off",
            "",
            "Local note:",
            (
                "If local TLS/certificate policy blocks pip-audit from contacting "
                "PyPI, use the Security Scan workflow evidence instead of recording "
                "a fake clean result."
            ),
        ]
    )
    DEPENDENCY_REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _iter_text_files() -> list[Path]:
    files: list[Path] = []
    for path in Path(".").rglob("*"):
        if not path.is_file():
            continue
        normalized = path.as_posix()
        if normalized in IGNORED_FILES:
            continue
        if any(part in IGNORED_DIRS for part in path.parts):
            continue
        files.append(path)
    return files


def _secret_patterns() -> list[re.Pattern[str]]:
    gh_prefix = "gh" + "p_"
    pat_prefix = "github" + "_pat_"
    token_words = "api[_-]?key|pass" + "word|sec" + "ret|tok" + "en"
    private_key = "begin (rsa|openssh|dsa|ec|private) private" + " key"
    return [
        re.compile(gh_prefix + r"[A-Za-z0-9_]{20,}"),
        re.compile(pat_prefix + r"[A-Za-z0-9_]{20,}"),
        re.compile(r"AKIA[0-9A-Z]{16}"),
        re.compile(private_key, re.IGNORECASE),
        re.compile(rf"({token_words})\s*[:=]\s*['\"][^'\"]{{8,}}", re.IGNORECASE),
    ]


def _run_secret_scan() -> list[str]:
    findings: list[str] = []
    patterns = _secret_patterns()
    for path in _iter_text_files():
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for pattern in patterns:
            for match in pattern.finditer(text):
                line_number = text.count("\n", 0, match.start()) + 1
                findings.append(f"{path.as_posix()}:{line_number}: {pattern.pattern}")

    if findings:
        SECRET_REPORT.write_text(
            "Potential credential findings:\n" + "\n".join(findings) + "\n",
            encoding="utf-8",
        )
    else:
        SECRET_REPORT.write_text(
            f"PASS: no hard-coded credential patterns found at {_timestamp()}.\n",
            encoding="utf-8",
        )
    return findings


def _docker_non_root_check() -> bool:
    dockerfile = Path("Dockerfile").read_text(encoding="utf-8")
    user_lines = [
        line.strip()
        for line in dockerfile.splitlines()
        if line.strip().upper().startswith("USER ")
    ]
    return bool(user_lines) and user_lines[-1].lower() not in {"user root", "user 0"}


def _write_docker_notes(non_root: bool) -> None:
    status = "PASS" if non_root else "FAIL"
    DOCKER_REPORT.write_text(
        "\n".join(
            [
                "# Docker Security Notes",
                "",
                f"Generated at: {_timestamp()}",
                "",
                f"- Non-root runtime user check: {status}",
                "- Dockerfile installs dependencies before switching to the runtime user.",
                "- The Flask/Gunicorn process runs under `USER appuser`.",
                "- Docker image vulnerability evidence is generated by the Security Scan workflow.",
                "- The image is still smoke-tested by the Docker Build and Deploy Kind workflows.",
                "",
                "This file is security evidence for the artefact. It does not claim that",
                "the image is free from every possible CVE; inspect the workflow scan",
                "artefacts for the current vulnerability output.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def _write_minimal_spdx_sbom() -> None:
    packages = _read_requirements()
    document = {
        "spdxVersion": "SPDX-2.3",
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": "mlops-wine-quality-pipeline-python-dependencies",
        "documentNamespace": (
            "https://github.com/lorcan973232/mlops-wine-quality-pipeline/"
            f"sbom/{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}"
        ),
        "creationInfo": {
            "created": _timestamp(),
            "creators": ["Tool: scripts/security_scan.py"],
        },
        "packages": [
            {
                "SPDXID": f"SPDXRef-Package-{name.lower().replace('_', '-')}",
                "name": name,
                "versionInfo": version,
                "downloadLocation": "NOASSERTION",
                "filesAnalyzed": False,
                "licenseConcluded": "NOASSERTION",
                "licenseDeclared": "NOASSERTION",
                "copyrightText": "NOASSERTION",
            }
            for name, version in packages
        ],
        "relationships": [
            {
                "spdxElementId": "SPDXRef-DOCUMENT",
                "relationshipType": "DESCRIBES",
                "relatedSpdxElement": f"SPDXRef-Package-{name.lower().replace('_', '-')}",
            }
            for name, _version in packages
        ],
    }
    SBOM_REPORT.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")


def _run_optional_pip_audit() -> int:
    command = [
        sys.executable,
        "-m",
        "pip_audit",
        "-r",
        "requirements.txt",
        "--progress-spinner",
        "off",
    ]
    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    output = completed.stdout + completed.stderr
    DEPENDENCY_REPORT.write_text(output or "pip-audit produced no output.\n", encoding="utf-8")
    return completed.returncode


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--run-pip-audit",
        action="store_true",
        help="Run pip-audit and fail if it reports vulnerabilities or cannot complete.",
    )
    args = parser.parse_args()

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    if args.run_pip_audit:
        audit_status = _run_optional_pip_audit()
    else:
        audit_status = 0
        _write_dependency_inventory()

    secret_findings = _run_secret_scan()
    docker_non_root = _docker_non_root_check()
    _write_docker_notes(docker_non_root)
    _write_minimal_spdx_sbom()

    if secret_findings:
        raise SystemExit("Potential credential patterns found.")
    if not docker_non_root:
        raise SystemExit("Dockerfile does not end with a non-root USER.")
    if audit_status != 0:
        raise SystemExit(audit_status)

    print("PASS: security evidence generated.")


if __name__ == "__main__":
    main()
